### ISSUE TITLE
Import photos hanging

### ISSUE THREAD

**Issue by shrouta** [aaronpk/OwnYourGram#38]
OwnYourGram was working for me until recently - first photos were registering with OYG but not posting to my known site, and now the photos tab just hangs with a spinning arrow.  Any help would be much appreciated!

**Comment by aaronpk** [comment]
Thanks, it looks like Instagram changed their HTML so I am updating the scraping to compensate.

**Comment by aaronpk** [comment]
This should be fixed in 201dab953f6e88877e9193aae68432c9c351face. I'm deploying it now!

**Comment by shrouta** [comment]
I'm still getting a note that there was an error posting the photo - but it's very possible I've missed something on my end.

**Comment by aaronpk** [comment]
I just tried importing an old photo of mine and it worked, so it might be something on your end. I think I see your site in the logs. Are you running the latest Known from GitHub, or the 0.9.2 release? 

For the old release, you'll need to change the OwnYourGram setting "send photos and videos as" to "Multipart upload" instead of "URLs". The URL option works with the latest GitHub version of Known but not the 0.9.2 release.
